
version: '3.4'

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
